services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: andersongt540
      POSTGRES_PASSWORD: Eikary24$
      POSTGRES_DB: tienda_app_bd
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U andersongt540 -d tienda_app_bd"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: node_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: